### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/virtualbox-docker-wsl2-switcher#2]
## TODO

- [x] Fix typo (`Hyper V` instead of `Hyper-V`)
- [x] Add info about spaces in paths where the repo is cloned to
- [x] Add info about Hyper-V support only on Windows 10 Pro (not Home)
